---
- hosts: localhost
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
          romkatv/powerlevel10k,
          homebrew/cask,
          adoptopenjdk/openjdk,
          #fishtown-analytics/dbt,
          #heroku/brew,
          #homebrew/cask-versions,
          #thoughtbot/formulae,
          #weaveworks/tap,
        ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - espanso
        - iterm2
        - mos
        - shureplus-motiv
        - visual-studio-code
        - brave-browser

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'zsh',
          'powerlevel10k',
          'openjdk@11',
        ]
        state: present
        update_homebrew: yes

    - name: Get the path to ZSH
      become: false
      local_action: command which zsh
      register: zsh_path

    - name: "Ensure homebrew zsh is in allowed shells"
      lineinfile:
        path: /etc/shells
        line: "{{ zsh_path.stdout }}"
      become: true

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

    - name: Set ZSH as the default shell
      shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
      become: true

    - name: "Create a default ZSH configuration"
      template:
        src: templates/.zshrc.j2
        dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: Import espanso profile
      copy:
        src: "~/OneDrive - VMware, Inc/Automator/macbootstrap/templates/espanso.yml"
        dest: "~/Library/Application Support/espanso/match/base.yml"